const genText = document.getElementById("gen-text")

genText.addEventListener("click", function() {
  let messages = [
    "My love for you is endless",
    "I love you",
    "Were perfect for each other",
    "I adore you",
    "You make my smile",
    "One day closer",
    "I cant wait to hold your hands",
    "Well see each other soon",
    "You complete me",
    "You are my soulmate",
    "Im proud to be yours",
    "You make me a better person",
    "I found love when I found you",
    "I got faith in you and I",
    "This love is a sure thing",
    "Want to be yours forever",
    "You make my heart melt",
    "You have my heart",
    "You mean the world to me",
    "Thank god I found you",
    "I love you to the moon and back",
    "you are perfect",
    "I will get you whatever you want",
    "You are the sweetest person ever",
    "I will love you Forever",
    "The more days go, the more I realized how lucky i was to come across you.",
    "I will always  be your number one fan",
    "I wish I was there with you!",
    "Im loving you more each and every day.",
    "It will always better when we are together.",
    "You are the reason for my smile.",
    "I cant wait to see you",
    "Your texts make my day  better.",
    "You make me the happiest person on Earth.",
    "You have no idea the amount of happiness you brought into my life.",
    "Call me anytime",
    "Distance means so little when someone means so much",
    "cant wait to go on our first date",
    "Thank you for saving my life",
    "You bring happiness into my life",
    "If not us then its not anybody else for me",
    "How did i get so lucky",
    "First date will be magical",
    "I love learnig new things about you",
    "You are so beautiful",
    "Got the most amazing and caring soul",
    "Even when the sky is falling",
    "Everything about you is just perfect",
    "I love how you care about my wellbeing",
    "My happiness is making you happy",
    "You are so cool",
    "Us being different makes us closer",
  ]
  const textEl = document.querySelector(".textMessage")
  textEl.textContent = messages[Math.floor( Math.random()*messages.length )]
})